name: send-to-server
on:
  push:
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.beget }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: npm i
      - run: npm run build
      - run: cd public
      - run: ls
      - run: ls
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress . webbeaver@webbeaver.beget.tech:/TEST